language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-grunt-static' ]; then cd .. && eval "mv $currentfolder generator-grunt-static" && cd generator-grunt-static; fi

